server:
  port: 3003
# do not left comma on last uri entry
filters: >
  http://stock_predict_service:12000/stock_predict,
  http://modality_service:12002/modality,
  http://fundamental_service:12004/fundamental,
  http://critic_service:12005/critic,
  http://user_score_service:12006/user_score,
  http://language_support_service:12003/language_support,
  http://games_released_service:12007/games_release
