server:
  port: 3003
# do not left comma on last uri entry
filters: >
  http://localhost:12000/stock_predict,
  http://localhost:12001/backtest,
  http://localhost:12002/modality,
  http://localhost:12003/expectation
